name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main  # Deploy on push to the main branch
  workflow_dispatch:  # Allow manual deployment triggers

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: webhook  # Set working directory for all steps

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Match the runtime stack in Azure

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      # Step 5: Deploy to Azure App Service
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: github-webhook  # Name of your Azure App Service
          slot-name: production     # Default slot
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
