name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main  # Deploy on push to the main branch
  workflow_dispatch:  # Allow manual deployment triggers

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: webhook  # Set working directory for all steps

    permissions:
      contents: read  # Required for actions/checkout
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies into app directory
        run: |
          mkdir -p app/
          pip install -r requirements.txt --target app/

      - name: Zip artifact for deployment
        run: zip release.zip ./app/* -r -x "*.git/*" "*.github/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d .

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'github-webhook'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}