name: Security Check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python version
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
      # run: |
      #   pip install safety bandit

    - name: Ensure script is executable
      run: chmod +x ./scripts/lint_python_projects.sh

    - name: Run lint script
      run: ./scripts/lint_python_projects.sh